### ISSUE TITLE
Embeds don't all seem to be working

### ISSUE THREAD

**Issue by florango** [adobe/helix-embed#145]
Check out this page:

https://helix-pipeline-adobe.project-helix.page/test/fixtures/embeds.html

The file embeds are working, but things like YouTube don't work.

**Comment by trieloff** [comment]
> It looks like this is an issue with the `helix-embed` service's configuration.

… but it isn't. It's a duplicate of https://github.com/adobe/helix-pipeline/issues/559, i.e. a missing `/` in the embed concatenation
