### ISSUE TITLE
Replace request with helix-fetch

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-embed#148]
Request is deprecated.

**Comment by MarquiseRosier** [comment]
@trieloff I'm already working on this with support for Lottie-Files; but this is blocked by https://github.com/adobe/helix-fetch/pull/12

**Comment by trieloff** [comment]
*made slightly inconvenient by…* adobe/helix-fetch#12

**Comment by trieloff** [comment]
Fixed in #164
