### ISSUE TITLE
Runtime action requires authentication

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-embed#198]
Just try to use the embed action: https://adobeioruntime.net/api/v1/web/helix/helix-services/embed@v1https://www.youtube.com/watch?v=KOxbO0EI4MA

You are being prompt with an authentication dialog which blocks other consuming actions.

Reason: the action is not deployed as a web action.

cc @stefan-guggisberg

**Comment by tripodsan** [comment]
the link is wrong. it should be:

https://adobeioruntime.net/api/v1/web/helix/helix-services/embed@v1/https://www.youtube.com/watch?v=KOxbO0EI4MA

**Comment by tripodsan** [comment]
see https://github.com/adobe/helix-pipeline/issues/559
