### ISSUE TITLE
Add SlideShare support

### ISSUE THREAD

**Issue by rofe** [adobe/helix-embed#208]
**Is your feature request related to a problem? Please describe.**
As a user, I would like to embed a SlideShare player in my content.

**Describe the solution you'd like**
I add the SlideShare URL as a link in my md or Word doc, and Helix turns it into a SlideShare player for me.

Example:
https://www.slideshare.net/adobe/adobe-digital-insights-holiday-recap-2019
would be transformed to the following output
```html
<iframe src="//www.slideshare.net/slideshow/embed_code/key/dG2YdReopAurYT" width="595" height="485" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC; border-width:1px; margin-bottom:5px; max-width: 100%;" allowfullscreen> </iframe>
```

**Additional context**
Needed for https://github.com/adobe/theblog/issues/166

**Comment by rofe** [comment]
@MarquiseRosier is this something you would like to tackle?

**Comment by MarquiseRosier** [comment]
Sure thing! :)

**Comment by rofe** [comment]
My bad - this actually already works ([thanks](https://github.com/adobe/theblog/issues/166#issuecomment-619819409) @trieloff!), we just need to whitelist slideshare.net in `helix-pipeline`
https://github.com/adobe/helix-pipeline/issues/693

**Comment by MarquiseRosier** [comment]
^^ Oh yeah i just saw that! Ok.
