### ISSUE TITLE
Add class name declaring the kind of embed used

### ISSUE THREAD

**Issue by rofe** [adobe/helix-embed#211]
**Is your feature request related to a problem? Please describe.**
Developers should be able to apply custom styles to different kinds of embeds. For this reason, it would come in handy if the embed's wrapper `div` got a distinct class name depending on the 2nd level domain in the hostname of the embed URL.

**Describe the solution you'd like**
A YouTube embed should have an `embed-youtube` class in the wrapper, a SlideShare embed an `embed-slideshare` class and so forth.

**Additional context**
Customer feedback on https://github.com/adobe/theblog/issues/166 was that the SoundCloud embed should be smaller when used on theblog.

**Comment by rofe** [comment]
@MarquiseRosier would you like to give it a shot?

**Comment by rofe** [comment]
Btw, I don't know what the `embed-advanced` class is actually used for. I think this one could be replaced with the "kind" class.

**Comment by rofe** [comment]
@MarquiseRosier any update? This would be nice to have for https://github.com/adobe/theblog/issues/179

**Comment by MarquiseRosier** [comment]
Sure, I can turn this in very soon! There's an issue with embeds, where some of the URLS that are on the whitelist don't go through the oembed service. So I'm going to try and fix that with this! :)
