### ISSUE TITLE
Support player urls

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-embed#218]
Follow up of the discussion here https://github.com/adobe/helix-pipeline/issues/702.

For any kind of embed, if the player url is provided (instead of the "direct" url to the resource), the embed service should be smart enough and use the player url as in the output.

**Comment by MarquiseRosier** [comment]
I’m interested in this! :)

**Comment by MarquiseRosier** [comment]
Reposting this, probably better here than in helix-chat

check https://iframely.com/features#domains to see what’s supported and just needs whitelisting!  :D

**Comment by kptdobe** [comment]
What is the status with this issue ? theblog has pages with the vimeo player that are NOT turned into embeds: see https://theblog--adobe.hlx.page/en/drafts/migrated/2018/04/05/contributor-spotlight-pierre-le-cann.html
