### ISSUE TITLE
Support Spotify embeds

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-embed#219]
See https://theblog.adobe.com/meet-the-ux-designers-jessica-moon-and-claude-piche

Required for adobe/theblog#186

**Comment by trieloff** [comment]
https://developer.spotify.com/documentation/widgets/generate/play-button/

Given a URL `https://open.spotify.com/playlist/37i9dQZF1DWYWddJiPzbvb` return a string
```html
<iframe src="https://open.spotify.com/embed/playlist/37i9dQZF1DWYWddJiPzbvb" width="300" height="380" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
```
