### ISSUE TITLE
some embeds don't go through iframely

### ISSUE THREAD

**Issue by MarquiseRosier** [adobe/helix-embed#231]
There is still an issue of some embeds not even going through Iframely which is strange; our embed script should be last ditch in case we cannot find an oembed. 

To be exact, https://www.youtube.com/embed/i_CMyAoNcRI shouldn't become
```
<div class="embed  embed-has-url embed-has-title">
  <a href="https://www.youtube.com/embed/i_CMyAoNcRI?">
    <span class="title">We’re Here. And We’re Ready | Coronavirus (COVID 19) Network Preparedness | Verizon - YouTube</span>
  </a>
<div>
```

It should become 
```
"<div class="embed embed-oembed embed-advanced"><div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%;"><iframe src="https://www.youtube.com/embed/TTCVn4EByfI?rel=0" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute;" allowfullscreen scrolling="no" allow="encrypted-media; accelerometer; gyroscope; picture-in-picture"></iframe></div></div>"
```

**Comment by trieloff** [comment]
Error logs in Coralogix and Traces in Epsagon show that the `api_key` parameter isn't appended to the URL.

**Comment by trieloff** [comment]
We only add the Iframely `api_key` when the request is made from the Fastly IP address range. As the intended use is for ESI resolution (which will be made from Fastly Edge nodes), this restricts unintended use.

You can verify by either using the service in Helix Pages, or by setting the `x-forwarded-for` header to an acceptable value.
