### ISSUE TITLE
query parameter bug

### ISSUE THREAD

**Issue by MarquiseRosier** [adobe/helix-embed#302]
**Description**
There is a bug in how we handle query parameters to reconstruct the embed url; particularly when there's overlap between critical parameters; in the querystring of the embed link and the actual query parameters that will go into the reconstruction. 

For example; with the following link: 

https://w.soundcloud.com/player/?url=https%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F857268679%3Fsecret_token%3Ds-L0YFl5jRCso&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true

This will be received in the following code snippets: 

https://github.com/adobe/helix-embed/blob/59e3c7095e97a09207329dacd3f36682fec6e223/src/index.js#L58-L68

this fails because url exists in both qs and queryParams so the following test fails: 

https://github.com/adobe/helix-embed/blob/59e3c7095e97a09207329dacd3f36682fec6e223/src/index.js#L83-L87

**Comment by kptdobe** [comment]
I assume this is what blocks https://github.com/adobe/theblog/issues/403.

**Comment by MarquiseRosier** [comment]
> I assume this is what blocks [adobe/theblog#403](https://github.com/adobe/theblog/issues/403).

Yes! :)

**Comment by tripodsan** [comment]
I suggest to solve it the same way as we do in data-embed, i.e. encode the entire URL and pass as single param.

eg: `?src=https%3A%2F%2Fw.soundcloud.com%2Fplayer%2F%3Furl%3Dhttps%253A%252F%252Fapi.soundcloud.com%252Ftracks%252F857268679%253Fsecret_token%253Ds-L0YFl5jRCso%26color%3D%2523ff5500%26auto_play%3Dfalse%26hide_related%3Dfalse%26show_comments%3Dtrue%26show_user%3Dtrue%26show_reposts%3Dfalse%26show_teaser%3Dtrue%26visual%3Dtrue`

**Comment by MarquiseRosier** [comment]
Also related; currently this but with query parameter processing is effecting critical attributes necessary for embeds like video.tv.adobe.com to be rendered with or without certain features!
