### ISSUE TITLE
enable propagation of queryparams!

### ISSUE THREAD

**Issue by MarquiseRosier** [adobe/helix-embed#320]
**Is your feature request related to a problem? Please describe.**
a user wants to be able to use the hidetitle=true queryparam in their iframe src; this exposes a new issue; currently we process query parameters and tack them back into a URL href; but sometimes Iframely removes these query params.

 I propose a kind of post processing to ensure query params that came with the video are always re-added to the src attribute in the iframe; I will check all possible embeds that we support to ensure that there are no adverse effects!

**Comment by tripodsan** [comment]
why attributes ? those are query params, rights ?
