### ISSUE TITLE
requests to fastly block and timeout after 60s

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-embed#326]
**Description**
![image](https://user-images.githubusercontent.com/917628/96212344-99dda580-0fb1-11eb-86a5-018902b91307.png)

**Comment by stefan-guggisberg** [comment]
We've seen problems with `https://api.fastly.com/public-ip-list` causing `ETIMEDOUT` repeatedly in the past. The endpoint seems to be unstable and we should not rely on it.
