### ISSUE TITLE
429s from Instagram

### ISSUE THREAD

**Issue by rofe** [adobe/helix-embed#346]
**Description**
We are getting a lot of 429s from Instagram. Not sure if this results in broken embeds, but we should investigate.

**To Reproduce**
https://app.epsagon.com/search?searchFilters%255B0%255D%255Bfilter%255D%3Dhttp.status_code%26searchFilters%255B0%255D%255Bop%255D%3D%253D%26searchFilters%255B0%255D%255Bvalue%255D%3D429%26searchFilters%255B1%255D%255Bop%255D%3D%253D%26searchFilters%255B1%255D%255Bfilter%255D%3Dresource_name%26searchFilters%255B1%255D%255Bvalue%255D%3Dwww.instagram.com%26timeFrame%3Dcustom%26startTime%3D1607402108096%26endTime%3D1607920808096%26interval%3D86400%26sort%255Bby%255D%3Dstart_time%26sort%255Bdirection%255D%3Ddesc

**Expected behavior**
No 429s from any 3rd party

**Comment by trieloff** [comment]
I don't think it's valid embeds. From how I read the traces it's either someone forgetting the post path (trying to just embed instagram.com) or someone maliciously using us as a proxy to probe the login page.
