### ISSUE TITLE
.vscode Folder Got Merged

### ISSUE THREAD

**Issue by sidhyatikku** [adobe/helix-embed#87]
**Description**
It seems that `.vscode` folder was not in `.gitignore` and now has been merged. This may impact other vscode users.

**To Reproduce**
1. Go to `adobe/helix`
2. Click on `/.vscode`
3. See the config files

I would like to work on this issue if it is a valid issue.

**Comment by tripodsan** [comment]
@sidhyatikku do you still work on this?
